"""add transaction time step

Revision ID: 9cb7bf07f7dd
Revises: 2710a0070ccd
Create Date: 2026-08-31 21:10:04.539408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cb7bf07f7dd'
down_revision: Union[str, Sequence[str], None] = '2710a0070ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('time_step', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'time_step')
    # ### end Alembic commands ###
